spring.application.name=scienceMedia

# Connexion à H2 (Base en mémoire, nommée 'testdb')
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Dialecte Hibernate spécifique à H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Gestion du schéma (create-drop est parfait pour H2 en mémoire)
spring.jpa.hibernate.ddl-auto=update

# --- Configuration de la Console H2 ---
# Accès via : http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Autorise l'accès à la console depuis un autre frame (nécessaire pour Spring Security si présent)
spring.h2.console.settings.web-allow-others=true

spring.jpa.show-sql=true


jwt.secretKey=VjYyaXk1VnorZDRJSzlveVVhcHVHMUhnUGhJd0lmeHJneDhXYTNyQ0pWcTBjQUh6NnFacHpFhZWRpZHNBbjFKcl
jwt.timeExpairation=100


